results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Success == true
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Parsed["logsource"] == "syslog"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Parsed["message"] == "pam_unix(webui:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=10.4.2.112"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Parsed["program"] == "synoscgi_SYNO.API.Auth_7_login"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Parsed["src_ip"] == "10.4.2.112"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Parsed["timestamp8601"] == "2022-02-09T20:53:37+01:00"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Parsed["pid"] == "2197"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Meta["log_type"] == "synology-dsm_failed_auth"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Meta["machine"] == "synologynas"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Meta["service"] == "synology-dsm"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Meta["source_ip"] == "10.4.2.112"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Meta["datasource_path"] == "synology-dsm-logs.log"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][0].Evt.Meta["datasource_type"] == "file"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Success == true
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Parsed["pid"] == "2209"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Parsed["src_ip"] == "10.4.2.112"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Parsed["logsource"] == "syslog"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Parsed["message"] == "pam_unix(webui:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=10.4.2.112"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Parsed["program"] == "synoscgi_SYNO.API.Auth_7_login"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Parsed["timestamp8601"] == "2022-02-09T20:53:48+01:00"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Meta["datasource_path"] == "synology-dsm-logs.log"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Meta["datasource_type"] == "file"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Meta["log_type"] == "synology-dsm_failed_auth"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Meta["machine"] == "synologynas"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Meta["service"] == "synology-dsm"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][1].Evt.Meta["source_ip"] == "10.4.2.112"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Success == true
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Parsed["pid"] == "2368"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Parsed["program"] == "synoscgi_SYNO.API.Auth_7_login"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Parsed["src_ip"] == "10.4.2.116"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Parsed["logsource"] == "syslog"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Parsed["message"] == "pam_unix(webui:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=10.4.2.116"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Parsed["timestamp8601"] == "2022-02-09T20:54:00+01:00"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Meta["datasource_path"] == "synology-dsm-logs.log"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Meta["datasource_type"] == "file"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Meta["log_type"] == "synology-dsm_failed_auth"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Meta["machine"] == "synologynas"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Meta["service"] == "synology-dsm"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][2].Evt.Meta["source_ip"] == "10.4.2.116"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Success == true
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Parsed["message"] == "pam_unix(webui:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=10.4.2.114"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Parsed["pid"] == "2706"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Parsed["logsource"] == "syslog"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Parsed["src_ip"] == "10.4.2.114"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Parsed["timestamp8601"] == "2022-02-09T20:55:08+01:00"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Parsed["program"] == "synoscgi_SYNO.API.Auth_7_login"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Meta["datasource_path"] == "synology-dsm-logs.log"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Meta["datasource_type"] == "file"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Meta["log_type"] == "synology-dsm_failed_auth"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Meta["machine"] == "synologynas"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Meta["service"] == "synology-dsm"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][3].Evt.Meta["source_ip"] == "10.4.2.114"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Success == true
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Parsed["program"] == "synoscgi_SYNO.API.Auth_7_login"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Parsed["src_ip"] == "10.4.2.113"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Parsed["timestamp8601"] == "2022-02-09T20:55:18+01:00"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Parsed["logsource"] == "syslog"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Parsed["message"] == "pam_unix(webui:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=10.4.2.113"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Parsed["pid"] == "2737"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Meta["datasource_path"] == "synology-dsm-logs.log"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Meta["datasource_type"] == "file"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Meta["log_type"] == "synology-dsm_failed_auth"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Meta["machine"] == "synologynas"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Meta["service"] == "synology-dsm"
results["s01-parse"]["crowdsecurity/synology-dsm-logs"][4].Evt.Meta["source_ip"] == "10.4.2.113"
